---
- hosts: all
  become: true
  tasks:

  - name: Update cache and Install apache2
    ansible.builtin.apt:
      name:
        - apache2
        - net-tools
      state: latest
      update_cache: yes
    when: ansible_distribution == "Kali" 

