---
- hosts: all
  become: true
  tasks:


  - name: Installation de vim nox
    ansible.builtin.apt:
      update_cache: yes
      name:
        - vim-nox
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
