---
- hosts: all
  become: true
  tasks:

  - name: Update repository index
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution == "Kali" 

  - name: Install apache2
    ansible.builtin.apt:
      name:
        - apache2
        - net-tools
      state: latest
    when: ansible_distribution == "Kali" 

