---
- hosts: all
  become: true
  tasks:

  - name: Update repository index
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution == "Kali" 

  - name: Install apache2
    ansible.builtin.apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Kali" 

  - name: Install net-tools
    ansible.builtin.apt:
      name: net-tools
    when: ansible_distribution == "Kali" 
