---
- hosts: all
  become: true
  tasks:

  - name: Update repository index
    ansible.builtin.apt:
      update_cache: yes

  - name: Remove apache2
    ansible.builtin.apt:
      name: apache2
      state: absent

  - name: Install net-tools
    ansible.builtin.apt:
      name: net-tools
