---
- hosts: all
  tags: always
  become: true
  tasks:

  - name: Mise à jour des serveurs
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution == "Kali"


  - name: Modification de fichier de conf
    ansible.builtin.lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: '^Timeout 400'
      line: Timeout 500


- hosts: all
  tags: web
  become: true
  tasks:

  - name: Installation de apache2 et net-tools
    ansible.builtin.apt:
      name:
        - apache2
        - net-tools
      state: latest
    when: ansible_distribution == "Kali"

  - name:  Copie d'une page web
    ansible.builtin.copy:
      src: /home/mhd/ansible_course/files/default_file.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 777

  - name: Verifier que apache est running
    ansible.builtin.service:
      name: apache2
      state: started
    when: ansible_distribution == "Kali"


- hosts: db_servers
  tags: db
  become: true
  tasks:

  - name: Installation de compo
    ansible.builtin.apt:
      name:
        - apache2
        - net-tools
      state: latest
    when: ansible_distribution == "Kali"
