---
- hosts: all
  become: true
  roles:
    - base


- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: database_servers
  become: true
  roles:
    - db_servers

- hosts: apache
  become: true
  roles:
    - geerlingguy.apache
